# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8108bff0fb09c7e5e8253a4fe0c8d1be1e982649c456be40e094a589e9a37f90ce24b814f3e294fc7cad6349c00786df1df32f70786b058104b084f5b950dc00

test:
  secret_key_base: f6d9ec3d37a90d39ec439bce853a32a26b4fa308f8d587d90e8f92d3e3cfe20d3127397cae8ec8495bc747791941ec33e4314c355a61139f4c38bc7252cb90a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
